# -*- coding: utf-8 -*-
"""Copia de Copia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7KtS7_1l5rJhwKpvGoesCHqEF6YrcN4

Taller - Instrucciones repetitivas en Python
Desarrolle la solucion a los siguientes problemas en Python, usando funciones y el programa correspondiente

Ejercicio 01
Una librería ofrece dos tipos de descuentos ante la compra de un libro. Si el libro tiene un precio inferior a cien mil pesos, el descuento es del 12% del precio; pero en cualquier otro caso, el descuento asciende a un 18%.

Escriba una función que halle el precio neto de un libro (precio menos descuento) de un libro, dado el precio del libro.
Ahora, escriba un programa que permita leer el precio de varios libros (finalizar cuando el precio es cero o negativo) y mostrar para cada libro, el precio neto (usando la función desarrollada anteriormente)
"""

# Definición de la función
def PrecioNeto(PrecioLibro: float) -> float:
    if PrecioLibro < 100000:
        PrecioNeto = PrecioLibro - (PrecioLibro*0.12)
    else:
        PrecioNeto = PrecioLibro - (PrecioLibro*0.18)
    return PrecioNeto


# Programa principal
PrecioLibro = float(input("Ingrese el precio del libro: "))
while PrecioLibro > 0:
    PrecioNetos = PrecioNeto(PrecioLibro)
    print("el precio neto es: ", PrecioNetos)
    PrecioLibro = float(input("Ingrese el precio del libro: "))

"""Ejercicio 02
Un vendedor recibe una comisión por el volumen de ventas que realice. Las reglas para asignarle la comisión al vendedor son las siguientes:

Ventas	Comisión
Inferior a 50 mil pesos	7% de las ventas
Entre 50 mil y 100 mil pesos	9% de las ventas más 5 mil pesos
Entre 100 mil y 200 mil pesos	11% de las ventas más 10 mil pesos
Entre 200 mil y 500 mil pesos	13% de las ventas más 20 mil pesos
Más de 500 mil pesos	15% de las ventas más 40 mil pesos
Escriba una función que recibe el valor de las ventas de un vendedor y que retorne la comisión
Escriba un programa que lea el valor de ventas de varios vendedores de la empresa (finalizar cuando las ventas sean negativas), y usando la función anterior, calcule la comisión y la imprima por pantalla.
"""

def Comision(ValorVentas:float)->float:
    if (ValorVentas<50000):
        Ganancia = ValorVentas * 0.07
    elif (50000<=ValorVentas<=100000):
        Ganancia = (ValorVentas * 0.09) + 5000
    elif (100001<=ValorVentas<200000):
        Ganancia = (ValorVentas * 0.11) + 10000
    elif (200001<=ValorVentas<=500000):
        Ganancia = (ValorVentas * 0.13) + 20000
    elif (ValorVentas>=500001):
        Ganancia = (ValorVentas * 0.15) + 40000
    return Ganancia

ValorVentas = float(input("Ingrese el valor de la venta"))

while 0<ValorVentas:
    Ganan = Comision(ValorVentas)
    print(f"El valor de la comison es de: {Ganan}")
    ValorVentas = float(input("Ingrese el valor de la venta"))

print("Final de programa")

"""Ejercicio 03
Una empresa ofrece a sus empleados un salario mensual fijo, y un porcertaje de las ventas como una comisión adicional a ese salario mensual. Esta comisión se calcula de la siguiente manera: si las ventas de un empleado excede los 50 mil pesoso, la comisión será de un 12% de las ventas que están por encima de los 50 mil pesos, en otro caso no habrá comisión.

Primero, construya una función en la que dado las ventas que hizo el empleado, determine cuánto es la comisión
Ahora hay que hacer un programa que calcule y muestre los salarios y comisiones de todos los empleados de la empresa. Para cada empleado hay que preguntarle al usuario, el salario mensual y las ventas realizadas, y mostrar la comisión por las ventas (usando la función anterior) y el salario neto (salario más comisión). Como no sabemos cuántos empleados hay, después de mostrar esta información, debemos preguntarle al usuario si desea seguir o no.
"""

# Definición de la función
def CalcularComision(SalarioFijo:float,Ventas:float)->(float,float):
  if(Ventas>=50000):
    Comision=Ventas*0.12
    SalarioNeto=SalarioFijo+Comision
  else:
    Comision=0
    SalarioNeto=SalarioFijo+Comision
  return Comision,SalarioNeto


# Programa principal
while True:
  Salario = int(input("Ingrese salario: "))
  if(Salario == 0):
    break
  Ventas = int(input("Ingrese ventas: "))
  Comison = CalcularComision(Salario,Ventas)
  print(f"Comision y salario neto es: {Comison}")

"""Ejercicio 04
En una empresa se le paga a los trabajadores al final de cada semana de acuerdo a las reglas dadas a continuación:

Si trabajas 35 horas o menos, se le paga un valor de 15 mil pesos la hora;
Si trabaja más de 35 horas pero menos de 60, el valor de la hora es de 15 mil por las primeras 35 horas y de 18 mil por cada hora trabajada por encima de las 35
Si trabaja más de 60 horas, las primeras 35 se pagan a 15 mil, las siguiente 25 horas a 18 mil cada una y las horas horas trabajadas por encima de las 60 horas, se le paga a 25 mil pesos cada una.
Vamos a buscar imprimir el salario semanal de cada uno de los empleados de la empresa. Para ello:

Escriba una función que reciba el número de horas trabajadas por un empleado y retorne el salario
Un programa que le pregunte al usuario el número de empleados que trabajan en la empresa, y para cada uno de esos, pregunte el número de horas trabajadas en la semana, y usando la función anterior, imprima el salario mensual de ese empleado.
"""

# Definición de la función
def Extras(Horas:int)->(int):
  if(Horas<=35):
    Extras = Horas*15000
  elif(35<Horas<60):
    Extras = Horas*18000
  elif(Horas>60):
    Extras = Horas*25000
  return Extras

# Programa principal
Empleados = 0
NumeroEmpleados = 0
Empleados = int(input("Ingrese numero de empleados: "))
while True:
  NumeroEmpleados += 1
  HorasSemana1 = int(input(f"Ingrese las horas extras trabajador # {NumeroEmpleados} semana uno: "))
  HorasSemana2 = int(input(f"Ingrese las horas extras trabajador # {NumeroEmpleados} semana dos: "))
  HorasSemana3 = int(input(f"Ingrese las horas extras trabajador # {NumeroEmpleados} semana tres: "))
  HorasSemana4 = int(input(f"Ingrese las horas extras trabajador # {NumeroEmpleados} semana cuatro: "))
  if(Empleados == NumeroEmpleados):
    break
  RecargoSemana1 = Extras(HorasSemana1)
  RecargoSemana2 = Extras(HorasSemana2)
  RecargoSemana3 = Extras(HorasSemana3)
  RecargoSemana4 = Extras(HorasSemana4)

  RecargoMensual = RecargoSemana1 + RecargoSemana2 + RecargoSemana3 + RecargoSemana4
  print(f"El pago mensual es de: {RecargoMensual} ")
print("\nPrograma terminado")